-- Update Cards Table to match entity structure
ALTER TABLE IF EXISTS cards DROP COLUMN IF EXISTS content;
ALTER TABLE IF EXISTS cards DROP COLUMN IF EXISTS author_id;
ALTER TABLE IF EXISTS cards ADD COLUMN IF NOT EXISTS title VARCHAR(255) NOT NULL;
ALTER TABLE IF EXISTS cards ADD COLUMN IF NOT EXISTS description TEXT;